spring:
  application:
    name: homepage
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  #DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SQL_URL}
    username: ${SQL_NAME}
    password: ${SQL_PASSWD}

  #JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

  #REDIS
  data:
    redis:
      host: localhost
      port: 6379
  #mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 60000 # 60000ms
        smtp.starttls.enable: true

project:
  folderPath: /upload

jwt:
  secret: ${JWT_SECRET};