spring:
  application:
    name: homepage

#DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payload?serverTimezone=Asia/Seoul
    username: root
    password: Q!W@E#r4t5

#JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

#REDIS
  data:
    redis:
      host: localhost
      port: 6379
#mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 60000 # 60000ms
        smtp.starttls.enable: true

project:
  folderPath: /upload
